//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Games
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabJogos
    {
        public int codigo { get; set; }
        public string NomeDoJogo { get; set; }
        public string Descricao { get; set; }
        public string LinkDaImagem { get; set; }
        public string Preço { get; set; }
        public string Plataformas { get; set; }
        public string Lojas { get; set; }
        public string VendasFeitas { get; set; }
    }
}
